# Generated by Django 4.2.1 on 2023-05-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('fb2', models.FileField(upload_to='book/fb2')),
                ('txt', models.FileField(upload_to='book/txt')),
            ],
        ),
    ]
